name: dcm_false_positive_cases
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  diffutil_dart: ^3.0.0

  flutter:
    sdk: flutter

  provider: ^6.0.5
  sub_package:
    path: ./packages/sub_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
